export const IS_LOAD = 'is_load'
export const USER_INFO = 'user_info'
export const MENU_LIST = 'menu_list'
export const CART_LIST = 'cart_list'
export const USER_ADRESS_LIST = 'user_adress_list'
export const USER_SELECT_ADDRESS = 'user_select_adress'
export const USER_ADD_ADDRESS = 'user_add_adress'
