let menu = [
  {
    type:"中餐",
    items:[
      {
        title:"炒饭",
        image:"/static/images/foods/cf.jpg",
        describe:"扬州炒饭",
        sales:100,
        price:15
      },
      {
        title:"炒面",
        image:"/static/images/foods/cm.jpg",
        describe:"美味炒面",
        sales:100,
        price:15
      },
      {
        title:"炒粉",
        image:"/static/images/foods/cfen.jpg",
        describe:"牛肉炒米粉",
        sales:100,
        price:15
      }
    ]
  },
  {
    type:"汉堡披萨",
    items:[
      {
        title:"板烧鸡腿堡",
        image:"/static/images/foods/hb.jpg",
        describe:"经典板烧鸡腿堡",
        sales:100,
        price:20
      },
      {
        title:"美式薯条",
        image:"/static/images/foods/st.jpg",
        describe:"薯条",
        sales:100,
        price:15
      },
      {
        title:"巨无霸",
        image:"/static/images/foods/jwb.jpg",
        describe:"双层牛肉巨无霸",
        sales:100,
        price:25
      }
    ]
  },
  {
    type:"饮料",
    items:[
      {
        title:"可乐",
        image:"/static/images/foods/kl.jpg",
        describe:"大杯可乐",
        sales:100,
        price:15
      },
      {
        title:"奶茶",
        image:"/static/images/foods/nc.jpg",
        describe:"快乐源泉",
        sales:100,
        price:15
      },
      {
        title:"柠檬茶",
        image:"/static/images/foods/nmc.jpg",
        describe:"肥宅快乐茶",
        sales:100,
        price:15
      }
    ]
  }
];

export default menu

